name: CI/CD Deployment on Self-Hosted Runner

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run Frontend Docker Container
        run: |
          cd frontend
          sudo docker stop frontend-cont || true
          sudo docker rm frontend-cont || true
          sudo docker build -t frontend-im:latest .
          sudo docker run -d --name frontend-cont -p 80:80 frontend-im:latest

  deploy-backend:
    name: Deploy Backend
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run Backend Docker Container
        run: |
          cd backend
          sudo docker stop backend-cont || true
          sudo docker rm backend-cont || true
          sudo docker build -t backend-im:latest .
          sudo docker run -d --name backend-cont -p 8001:8000 backend-im:latest
