name: CI/CD Deployment on Self-Hosted Runner

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: self-hosted
    if: contains(github.event.head_commit.modified, 'frontend/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run Frontend Docker Container
        run: |
          cd frontend
          sudo docker stop frontend-con || true
          sudo docker rm frontend-con || true
          sudo docker build -t frontend:latest .
          sudo docker run -d --name frontend-con -p 3001:3000 frontend:latest

  deploy-backend:
    name: Deploy Backend
    runs-on: self-hosted
    if: contains(github.event.head_commit.modified, 'backend/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run Backend Docker Container
        run: |
          cd backend
          sudo docker stop backend-con || true
          sudo docker rm backend-con || true
          sudo docker build -t backend:latest .
          sudo docker run -d --name backend-con -p 8000:8000 backend:latest
