name: CI/CD Deployment on Self-Hosted Runner

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run Frontend Docker Container
        run: |
          cd frontend
          sudo docker stop frontend || true
          sudo docker rm frontend || true
          sudo docker build -t frontend-img:latest .
          sudo docker run -d --name frontend -p 80:80 frontend-img:latest

  deploy-backend:
    name: Deploy Backend
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run Backend Docker Container
        run: |
          cd backend
          sudo docker stop backend || true
          sudo docker rm backend || true
          sudo docker build -t backend-img:latest .
          sudo docker run -d --name backend -p 8001:8000 backend-img:latest
